/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MouseHook */

#ifndef _Included_MouseHook
#define _Included_MouseHook
#ifdef __cplusplus
extern "C" {
#endif
#undef MouseHook_WM_LBUTTONDOWN
#define MouseHook_WM_LBUTTONDOWN 513L
#undef MouseHook_WM_LBUTTONUP
#define MouseHook_WM_LBUTTONUP 514L
#undef MouseHook_WM_RBUTTONDOWN
#define MouseHook_WM_RBUTTONDOWN 516L
#undef MouseHook_WM_RBUTTONUP
#define MouseHook_WM_RBUTTONUP 517L
/*
 * Class:     MouseHook
 * Method:    registerHook
 * Signature: (LGlobalMouseListener;)V
 */
JNIEXPORT void JNICALL Java_MouseHook_registerHook
  (JNIEnv *, jobject, jobject);

/*
 * Class:     MouseHook
 * Method:    unregisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MouseHook_unregisterHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
