/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestHookJNI */

#ifndef _Included_TestHookJNI
#define _Included_TestHookJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestHookJNI
 * Method:    mousePosition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestHookJNI_mousePosition
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
